version: '3.4'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-fastapi
    volumes:
      - ./api:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13.1-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  default:
    name: bridge
  backend:
    name: backend
    driver: bridge
    external: true

volumes:
    postgres_data: