version: '3.4'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./api/.env
    ports:
      - 8008:8000
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  default:
    name: bridge
  backend:
    name: backend
    driver: bridge
    external: true

volumes:
    postgres_data: